spring.application.name=tejidos

# Configuración de conexión para XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/beris_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


